---
- hosts: 172.31.5.35
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:

  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: Install git
    yum:
      name: git
      state: present

  - name: Install maven
    yum:
      name: maven
      state: latest

  - name: Install docker
    yum:
      name: docker
      state: present
  - name: 
    service:
      name: docker
      state: started